// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCocBxp3n3IwhMuZxIdKJ1vrFpy_172rk4',
    appId: '1:393556616343:web:6f44cddcbbf627f5af75d2',
    messagingSenderId: '393556616343',
    projectId: 'quickhelp-df8ca',
    authDomain: 'quickhelp-df8ca.firebaseapp.com',
    storageBucket: 'quickhelp-df8ca.firebasestorage.app',
    measurementId: 'G-DJ19K1V3C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvCompmJ8tccqQ-YVSMkE0xqsOfemDIKM',
    appId: '1:393556616343:android:35829de881a06c33af75d2',
    messagingSenderId: '393556616343',
    projectId: 'quickhelp-df8ca',
    storageBucket: 'quickhelp-df8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4lZMtFWhBdTVYxa1dTSBIy_-LsrGhAg',
    appId: '1:393556616343:ios:578509a28895cfc2af75d2',
    messagingSenderId: '393556616343',
    projectId: 'quickhelp-df8ca',
    storageBucket: 'quickhelp-df8ca.firebasestorage.app',
    androidClientId: '393556616343-i1355m45bt5vouv07dcj7l090c8fn7uk.apps.googleusercontent.com',
    iosClientId: '393556616343-ue82o04f6mbt5a7gbbv3g4vr0hc5qv9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC4lZMtFWhBdTVYxa1dTSBIy_-LsrGhAg',
    appId: '1:393556616343:ios:578509a28895cfc2af75d2',
    messagingSenderId: '393556616343',
    projectId: 'quickhelp-df8ca',
    storageBucket: 'quickhelp-df8ca.firebasestorage.app',
    androidClientId: '393556616343-i1355m45bt5vouv07dcj7l090c8fn7uk.apps.googleusercontent.com',
    iosClientId: '393556616343-ue82o04f6mbt5a7gbbv3g4vr0hc5qv9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCocBxp3n3IwhMuZxIdKJ1vrFpy_172rk4',
    appId: '1:393556616343:web:cdcaf17ea1648db4af75d2',
    messagingSenderId: '393556616343',
    projectId: 'quickhelp-df8ca',
    authDomain: 'quickhelp-df8ca.firebaseapp.com',
    storageBucket: 'quickhelp-df8ca.firebasestorage.app',
    measurementId: 'G-9Z9CD9WLPR',
  );

}